plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.bardopdf'
version = '1.0.0'

android {
  namespace "expo.modules.bardopdf"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // Pdfium nativo: texto por página, índice y metadatos.
  implementation 'io.legere:pdfiumandroid:1.0.35'
}
