import { describe, expect, it } from 'vitest';

import { buildAutoSummary, cleanMetadataSummary } from './bookSummary';

const NL = String.fromCharCode(10);
const parrafo = (texto: string) => texto;
const libro = (...parrafos: string[]) => parrafos.join(NL + NL);

const PROSA =
  'El viajero llegó al pueblo cuando caía la tarde y las primeras luces se encendían en las ventanas. ' +
  'Nadie lo esperaba, y sin embargo todos parecían saber quién era y a qué había venido desde tan lejos.';

describe('buildAutoSummary', () => {
  it('toma el primer párrafo de prosa', () => {
    const texto = libro(PROSA, 'Otro párrafo que no importa.');
    expect(buildAutoSummary(texto)).toContain('El viajero llegó al pueblo');
  });

  it('saltea el título en mayúsculas', () => {
    const texto = libro('DON QUIJOTE DE LA MANCHA, PRIMERA PARTE DE LA OBRA COMPLETA EN CASTELLANO', PROSA);
    const resumen = buildAutoSummary(texto);
    expect(resumen).not.toContain('DON QUIJOTE');
    expect(resumen).toContain('El viajero');
  });

  it('saltea los preliminares', () => {
    const texto = libro(
      parrafo('Este libro electrónico es para el uso de cualquiera en cualquier lugar del Proyecto Gutenberg, sin costo alguno y sin restricciones.'),
      parrafo('Todos los derechos reservados. Ninguna parte de esta publicación puede ser reproducida sin permiso escrito de la editorial correspondiente.'),
      PROSA,
    );
    const resumen = buildAutoSummary(texto);
    expect(resumen).not.toMatch(/Gutenberg|derechos reservados/i);
    expect(resumen).toContain('El viajero');
  });

  it('saltea los renglones cortos (títulos, nombres sueltos)', () => {
    const texto = libro('Capítulo 1', 'El bosque', PROSA);
    expect(buildAutoSummary(texto)).toContain('El viajero');
  });

  it('corta en fin de oración y no pasa del largo máximo', () => {
    const largo = PROSA + ' ' + PROSA + ' ' + PROSA;
    const resumen = buildAutoSummary(largo)!;
    expect(resumen.length).toBeLessThanOrEqual(320);
    expect(resumen.endsWith('.') || resumen.endsWith('…')).toBe(true);
  });

  it('lo que devuelve está tal cual en el libro', () => {
    const texto = libro(PROSA);
    const resumen = buildAutoSummary(texto)!;
    const sinPuntos = resumen.replace(/…$/, '');
    expect(texto.replace(/\s+/g, ' ')).toContain(sinPuntos);
  });

  it('un texto muy corto o vacío no da resumen', () => {
    expect(buildAutoSummary('')).toBeNull();
    expect(buildAutoSummary('Hola.')).toBeNull();
  });

  it('un libro que es solo preliminares no da resumen', () => {
    const texto = libro(
      'Todos los derechos reservados. Ninguna parte de esta publicación puede ser reproducida ni transmitida sin permiso.',
      'Copyright 2020 de la editorial, con domicilio legal en la ciudad donde se imprimió por primera vez este volumen.',
    );
    expect(buildAutoSummary(texto)).toBeNull();
  });
});

describe('cleanMetadataSummary', () => {
  it('saca el HTML que traen muchos EPUB', () => {
    expect(cleanMetadataSummary('<p>Una novela sobre <b>el tiempo</b> y la memoria de un pueblo.</p>')).toBe(
      'Una novela sobre el tiempo y la memoria de un pueblo.',
    );
  });

  it('junta los espacios y los saltos', () => {
    expect(cleanMetadataSummary('Una   novela' + NL + 'sobre el tiempo y la memoria.')).toBe(
      'Una novela sobre el tiempo y la memoria.',
    );
  });

  it('la firma de la herramienta no es una sinopsis', () => {
    // Lo que meten Word, calibre o python-docx cuando el autor no puso nada.
    for (const basura of [
      'generated by python-docx, the library used to build this document',
      'Created with LibreOffice Writer version 7 for the desktop edition',
      'Microsoft Word - documento final revisado por el equipo editorial',
      'Converted from HTML by an automated pipeline of the publisher',
    ]) {
      expect(cleanMetadataSummary(basura)).toBeNull();
    }
  });

  it('una sinopsis de verdad sí cuenta', () => {
    expect(cleanMetadataSummary('Una novela sobre el tiempo y la memoria de un pueblo del sur.')).toBe(
      'Una novela sobre el tiempo y la memoria de un pueblo del sur.',
    );
  });

  it('una sinopsis vacía o demasiado corta no cuenta', () => {
    expect(cleanMetadataSummary(null)).toBeNull();
    expect(cleanMetadataSummary('')).toBeNull();
    expect(cleanMetadataSummary('Novela')).toBeNull();
  });

  it('recorta la que es demasiado larga', () => {
    const larga = 'Una novela extensa sobre el tiempo. '.repeat(40);
    expect(cleanMetadataSummary(larga)!.length).toBeLessThanOrEqual(320);
  });
});
